### ISSUE TITLE
Make JavaClient available on Maven Central

### ISSUE THREAD

**Issue by richarda23** [swordapp/JavaClient2.0#4]
Hi, Just wondered if you could put this project on MavenCentral? We use this library to upload files to Dataverse and DSpace repositories  and it would be nice if it could be added as a regular dependency.

**Comment by richard-jones** [comment]
Yes, that would be a good idea.  The only issue is time - I'll try to find some!

**Comment by richard-jones** [comment]
Just to let you know, I'm currently working on this.  I found two limitations this week with the library, so I've fixed them and I'm in the process of getting this new version (which will be 0.9.3, and fully back compatible with 0.9.2) up via sonotype.  Just waiting for them to do some admin.

**Comment by richarda23** [comment]
That's great, look forward to trying it out. Thanks for doing this.

**Comment by richard-jones** [comment]
Now available on maven central.

groupId: org.swordapp
artifactId: sword2-client
version: 0.9.3

https://repo1.maven.org/maven2/org/swordapp/


Now I've got the process set up, I'll be sure to publish updates as they become available.  Slow moving library, though, so I'd expect 0.9.3 to be the latest version for a while.

**Comment by otter606** [comment]
Perfect, thank you, works fine!
